from enum import StrEnum


class QueryFamily(StrEnum):
    DIRECT_CANONICAL = "DIRECT_CANONICAL"
    SYNONYM_ACRONYM = "SYNONYM_ACRONYM"
    FUNCTIONAL = "FUNCTIONAL"
    MECHANISM = "MECHANISM"
    RELATIONSHIP = "RELATIONSHIP"
    OUTCOME_OBJECTIVE = "OUTCOME_OBJECTIVE"
    HISTORICAL_TERMINOLOGY = "HISTORICAL_TERMINOLOGY"
    ADJACENT_DOMAIN = "ADJACENT_DOMAIN"
    COMPONENT = "COMPONENT"
    COMBINATION = "COMBINATION"
    ENTITY_DISCOVERY = "ENTITY_DISCOVERY"
