from enum import Enum


class AssessmentStage(str, Enum):
    RECEIVED = "RECEIVED"
    NORMALIZED = "NORMALIZED"
    SUFFICIENCY_ASSESSED = "SUFFICIENCY_ASSESSED"
    MCU_DECOMPOSED = "MCU_DECOMPOSED"
    MCU_RECONCILED = "MCU_RECONCILED"
    SEARCH_PLANNED = "SEARCH_PLANNED"
    SEARCH_PLAN_REVIEWED = "SEARCH_PLAN_REVIEWED"
    SCREENING = "SCREENING"
    ADAPTIVE_RESEARCH = "ADAPTIVE_RESEARCH"
    EVIDENCE_NORMALIZED = "EVIDENCE_NORMALIZED"
    EVIDENCE_MAPPED = "EVIDENCE_MAPPED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    ADVERSARIAL_CHALLENGE = "ADVERSARIAL_CHALLENGE"
    DEFENCE_REVIEW = "DEFENCE_REVIEW"
    PRELIMINARY_ADJUDICATION = "PRELIMINARY_ADJUDICATION"
    ROBUSTNESS_REVIEW = "ROBUSTNESS_REVIEW"
    FINDINGS_FROZEN = "FINDINGS_FROZEN"
    REPORTED = "REPORTED"


class AssessmentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PARTIAL = "PARTIAL"
    ABSTAINED = "ABSTAINED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class SufficiencyState(str, Enum):
    INSUFFICIENT = "INSUFFICIENT"
    EXPLORATORY = "EXPLORATORY"
    ASSESSABLE = "ASSESSABLE"
    HIGH_RESOLUTION = "HIGH_RESOLUTION"


class ResearchDepth(str, Enum):
    INACTIVE = "INACTIVE"
    SCREENING = "SCREENING"
    STANDARD = "STANDARD"
    DEEP = "DEEP"
    ESCALATED = "ESCALATED"
    SATURATED = "SATURATED"
    BUDGET_STOPPED = "BUDGET_STOPPED"
    ACCESS_BLOCKED = "ACCESS_BLOCKED"


class ResearchMode(str, Enum):
    QUICK = "QUICK"
    STANDARD = "STANDARD"
    DEEP = "DEEP"
    MAXIMUM = "MAXIMUM"


class EvidenceFamily(str, Enum):
    SCHOLARLY = "SCHOLARLY"
    PATENT = "PATENT"
    SOFTWARE = "SOFTWARE"
    PRODUCT = "PRODUCT"
    GENERAL_WEB = "GENERAL_WEB"
    STANDARDS = "STANDARDS"
    REGULATORY_GOVERNMENT = "REGULATORY_GOVERNMENT"
    GREY_LITERATURE = "GREY_LITERATURE"
    HISTORICAL_ARCHIVAL = "HISTORICAL_ARCHIVAL"


class EvidenceTier(str, Enum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"


class ValueMaturity(str, Enum):
    CLAIMED = "CLAIMED"
    PLAUSIBLE = "PLAUSIBLE"
    SUPPORTED = "SUPPORTED"
    DEMONSTRATED = "DEMONSTRATED"


class PrecedentState(str, Enum):
    DIRECT_PRECEDENT = "DIRECT_PRECEDENT"
    STRONG_PARTIAL_PRECEDENT = "STRONG_PARTIAL_PRECEDENT"
    COMPONENT_PRECEDENT_ONLY = "COMPONENT_PRECEDENT_ONLY"
    ANALOGOUS_PRECEDENT = "ANALOGOUS_PRECEDENT"
    SUPERFICIAL_SIMILARITY = "SUPERFICIAL_SIMILARITY"
    NO_DIRECT_PRECEDENT_IDENTIFIED = "NO_DIRECT_PRECEDENT_IDENTIFIED"
    CONTRADICTORY_EVIDENCE = "CONTRADICTORY_EVIDENCE"
    UNRESOLVED = "UNRESOLVED"
    UNASSESSABLE = "UNASSESSABLE"


class SupportVerificationState(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"
    CONTRADICTED = "CONTRADICTED"


class VerdictState(str, Enum):
    STRONG_EVIDENCE_OF_NOVELTY = "STRONG_EVIDENCE_OF_NOVELTY"
    POTENTIALLY_NOVEL = "POTENTIALLY_NOVEL"
    MIXED_CONTRIBUTION_SPECIFIC = "MIXED_CONTRIBUTION_SPECIFIC"
    NOT_NOVEL_AT_CLAIMED_LEVEL = "NOT_NOVEL_AT_CLAIMED_LEVEL"
    UNASSESSABLE = "UNASSESSABLE"


class TraceStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    SKIPPED = "SKIPPED"
    DEGRADED = "DEGRADED"


class FailureClass(str, Enum):
    INPUT_SPECIFICATION_FAILURE = "INPUT_SPECIFICATION_FAILURE"
    MCU_DECOMPOSITION_INSTABILITY = "MCU_DECOMPOSITION_INSTABILITY"
    QUERY_GENERATION_FAILURE = "QUERY_GENERATION_FAILURE"
    SEARCH_PLAN_REVIEW_FAILURE = "SEARCH_PLAN_REVIEW_FAILURE"
    SOURCE_ACCESS_FAILURE = "SOURCE_ACCESS_FAILURE"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    SOURCE_COVERAGE_FAILURE = "SOURCE_COVERAGE_FAILURE"
    LANGUAGE_COVERAGE_FAILURE = "LANGUAGE_COVERAGE_FAILURE"
    TEMPORAL_COVERAGE_FAILURE = "TEMPORAL_COVERAGE_FAILURE"
    DOMAIN_TERMINOLOGY_FAILURE = "DOMAIN_TERMINOLOGY_FAILURE"
    EVIDENCE_EXTRACTION_FAILURE = "EVIDENCE_EXTRACTION_FAILURE"
    EVIDENCE_SUPPORT_FAILURE = "EVIDENCE_SUPPORT_FAILURE"
    PROVENANCE_AMBIGUITY = "PROVENANCE_AMBIGUITY"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    LOW_SOURCE_QUALITY = "LOW_SOURCE_QUALITY"
    SEARCH_NON_SATURATION = "SEARCH_NON_SATURATION"
    BUDGET_EXHAUSTION = "BUDGET_EXHAUSTION"
    ADJUDICATION_INSTABILITY = "ADJUDICATION_INSTABILITY"
    ROBUSTNESS_TEST_FAILURE = "ROBUSTNESS_TEST_FAILURE"
