from typing import Protocol, runtime_checkable

from novelty_harness.ports.models import CitationResult, SourceRef


@runtime_checkable
class CitationProvider(Protocol):
    @property
    def name(self) -> str: ...
    async def backward_citations(self, source_ref: SourceRef) -> CitationResult: ...
    async def forward_citations(self, source_ref: SourceRef) -> CitationResult: ...
    async def related(self, source_ref: SourceRef) -> CitationResult: ...
